@startuml mascota 

Class Mascota 
Class Alimento
Class Carne 
Class Juguete
Class Animal
Class Pelota 
Class Dueño
Class Rastreador
Class Jabon  
Class Cama
Class hueso
Class Casa 
Class pelaje 
Class Agua 
Class Premios
Class Humano

Mascota --|> Animal
Carne --|> Alimento
Pelota --|> Juguete
Humano --|> Dueño
Hueso --|> Premios
Premo --|> Alimento
Mascota *--o Rastreador
Mascota *--o Dueño
Mascota *--o Casa
Mascota *--o pelaje
Mascota *--o Premios
Mascota --o Jabon
Mascota --o Cama
Mascota --o Carne
Mascota --o Pelota
Mascota --o Agua
Mascota --o Hueso

@enduml
